//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooldozerCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooldozerCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MapSelect&gt;
        ///	&lt;MapSelectEntry&gt;
        ///		&lt;InternalName&gt;map0&lt;/InternalName&gt;
        ///		&lt;EnglishName&gt;Test Map&lt;/EnglishName&gt;
        ///	&lt;/MapSelectEntry&gt;
        ///	&lt;MapSelectEntry&gt;
        ///		&lt;InternalName&gt;map1&lt;/InternalName&gt;
        ///		&lt;EnglishName&gt;E. Gadd&apos;s Lab&lt;/EnglishName&gt;
        ///	&lt;/MapSelectEntry&gt;
        ///	&lt;MapSelectEntry&gt;
        ///		&lt;InternalName&gt;map2&lt;/InternalName&gt;
        ///		&lt;EnglishName&gt;Mansion&lt;/EnglishName&gt;
        ///	&lt;/MapSelectEntry&gt;
        ///	&lt;MapSelectEntry&gt;
        ///		&lt;InternalName&gt;map3&lt;/InternalName&gt;
        ///		&lt;EnglishName&gt;Training Room&lt;/EnglishName&gt;
        ///	&lt;/MapSelectEntry&gt;
        ///	&lt;MapSelectEntry&gt;
        ///		&lt;Internal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapSelectDatabase {
            get {
                return ResourceManager.GetString("MapSelectDatabase", resourceCulture);
            }
        }
    }
}
